// <auto-generated />
namespace Invoicing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _141 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_141));
        
        string IMigrationMetadata.Id
        {
            get { return "201608191852024_141"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
