// <auto-generated />
namespace Invoicing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _134 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_134));
        
        string IMigrationMetadata.Id
        {
            get { return "201608180654575_134"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
