// <auto-generated />
namespace Invoicing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _149 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_149));
        
        string IMigrationMetadata.Id
        {
            get { return "201608241759124_149"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
